# Llama 3.3 70B Instruct Configuration
name: "llama3.3:70b-instruct"

resources:
  gpu_layers: 80
  gpu_memory: "80GB"
  batch_size: 2
  max_concurrent: 1

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["###"]  # Default stop sequence

system:
  prompt: "You are a helpful AI assistant. You are direct, accurate, and helpful in your responses."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 4]
  concurrent_range: [1, 2]

# Resource Requirements
requirements:
  min_gpu_memory: "80GB"  # Minimum required for safe operation
  recommended_gpu: "A100-80GB"  # Requires high-end GPUs
  cuda_version: ">=11.7"
  cpu_threads: 8
  gpu_memory_utilization: 0.9 