# Mistral Large 123B Configuration
name: "mistral-large:123b"

resources:
  gpu_layers: 48
  gpu_memory: "80GB"
  batch_size: 1
  max_concurrent: 1

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["[INST]", "[/INST]", "</s>"]  # Default stop sequence

system:
  prompt: "You are a helpful AI assistant. You are direct, accurate, and helpful in your responses."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 1]
  concurrent_range: [1, 1]

# Resource Requirements
requirements:
  min_gpu_memory: "80GB"  # Minimum required for safe operation
  recommended_gpu: "A100-80GB"
  cuda_version: ">=12.0"
  cpu_threads: 16
  gpu_memory_utilization: 0.9 