# Llama 3.2 Vision 11B Configuration
name: "llama3.2-vision:11b"

resources:
  gpu_layers: 50
  gpu_memory: "24GB"
  batch_size: 4
  max_concurrent: 2

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["###"]  # Default stop sequence from test_prompts.json

system:
  prompt: "You are a helpful AI assistant with vision capabilities. You can understand both text and images provided by the user. Answer accurately and helpfully based on the visual and textual information."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 8]
  concurrent_range: [1, 4]

# Resource Requirements
requirements:
  min_gpu_memory: "24GB"  # Minimum required for safe operation
  recommended_gpu: "A100"
  cuda_version: ">=12.0"
  cpu_threads: 8
  gpu_memory_utilization: 0.9 