# Llama 3.2 Vision 90B Configuration
name: "llama3.2-vision:90b"

resources:
  gpu_layers: 80
  gpu_memory: "40GB"
  batch_size: 2
  max_concurrent: 1

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["###"]  # Default stop sequence from test_prompts.json

system:
  prompt: "You are a helpful AI assistant with vision capabilities. You can understand both text and images provided by the user. Answer accurately and helpfully based on the visual and textual information."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 4]
  concurrent_range: [1, 2]

# Resource Requirements
requirements:
  min_gpu_memory: "40GB"  # Minimum required for safe operation
  recommended_gpu: "A100"
  cuda_version: ">=12.0"
  cpu_threads: 16
  gpu_memory_utilization: 0.9 