title: AI-Flux Documentation
description: Documentation for AI-Flux - LLM Batch Processing Pipeline for HPC Systems
url: https://aiflux.ncsa.ai
baseurl: ""
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge 