title: AI-Flux Documentation
description: Documentation for AI-Flux - LLM Batch Processing Pipeline for HPC Systems
url: https://aiflux.ncsa.ai
baseurl: ""
remote_theme: pages-themes/minimal
github:
  repository_url: https://github.com/UIUC-Chatbot/ai-flux
  is_project_page: true
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge 