# Mistral Nemo 12B Configuration
name: "mistral-nemo:12b"

resources:
  gpu_layers: 40
  gpu_memory: "16GB"
  batch_size: 4
  max_concurrent: 2

parameters:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 2048
  stop_sequences: ["###"]  # Default stop sequence

system:
  prompt: "You are a helpful AI assistant. You are direct, accurate, and helpful in your responses."

validation:
  temperature_range: [0.0, 1.0]
  max_tokens_limit: 4096
  batch_size_range: [1, 8]
  concurrent_range: [1, 4]

# Resource Requirements
requirements:
  min_gpu_memory: "16GB"  # Minimum required for safe operation
  recommended_gpu: "A100"
  cuda_version: ">=11.7"
  cpu_threads: 6
  gpu_memory_utilization: 0.9 